/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game */

#ifndef _Included_Game
#define _Included_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game
 * Method:    loadSpriteFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Game_loadSpriteFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Game
 * Method:    createWidget
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[[Ljava/lang/Float;Ljava/lang/Float;Ljava/lang/Float;Ljava/lang/Float;Ljava/lang/Float;)V
 */
JNIEXPORT void JNICALL Java_Game_createWidget
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
